// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PassportService.Infrastructure;

#nullable disable

namespace PassportService.Migrations
{
    [DbContext(typeof(PassportDbContext))]
    partial class PassportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PassportService.Core.Passport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<DateTime>>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone[]");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<DateTime>>("RemovedAt")
                        .HasColumnType("timestamp with time zone[]");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Passports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new List<DateTime> { new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc) },
                            Number = "567890",
                            Series = "1234"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new List<DateTime> { new DateTime(2019, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc) },
                            Number = "678901",
                            RemovedAt = new List<DateTime> { new DateTime(2022, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc) },
                            Series = "2345"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new List<DateTime> { new DateTime(2021, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc) },
                            Number = "789012",
                            Series = "3456"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new List<DateTime> { new DateTime(2018, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc) },
                            Number = "890123",
                            RemovedAt = new List<DateTime> { new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc) },
                            Series = "4567"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new List<DateTime> { new DateTime(2022, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc) },
                            Number = "901234",
                            Series = "5678"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new List<DateTime> { new DateTime(2020, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc) },
                            Number = "012345",
                            Series = "6789"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new List<DateTime> { new DateTime(2021, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc) },
                            Number = "123456",
                            RemovedAt = new List<DateTime> { new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc) },
                            Series = "7890"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new List<DateTime> { new DateTime(2019, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc) },
                            Number = "234567",
                            Series = "8901"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
