name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore PassportService.sln

      - name: Build the solution
        run: dotnet build PassportService.sln --configuration Release

      - name: Run tests
        run: dotnet test PassportService.sln --verbosity normal
